# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: pre-commit
        name: pre-commit
        entry: pipenv run pre-commit
        language: system
        types: [python]